map_type: costmap
transform_tolerance: 2.0
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [-0.2, -0.2], [-0.2, -0.2], [0.2, 0.2], [0.2, -0.2]]
footprint_inflation: 0.01
robot_radius: 0.2
inflation_radius: 0.15
max_obstacle_height: 0.6
min_obstacle_height: 0.0
lethal_cost_threshold: 100
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
